### ISSUE TITLE
Master libp2p Docs Issue

### ISSUE THREAD

**Issue by ghost** [libp2p/docs#233]
This is a master issue to track docs improvements we need on libp2p.  tl;dr We have many friends and fans at Web3 and DevCon4, and the number one request we hear is to create more docs, diagrams, architectural overviews, videos, etc.  Let's fix that!

- [ ] Video and/or diagrammatic explanation of @raulk  "story of a node" from DevCon4
- [ ] libp2p/libp2p#53 (diagrams explaining pubsub protocol)
- [ ] libp2p/libp2p#54 (libp2p conceptual overview diagrams)
- [ ] [Diagram showing the ping-pong sequence](https://drive.google.com/file/d/0B14bpN1SbBuQQzJuNlVBM21RcGQtSUJIaU5ERzV1N193VlU0/view?usp=sharing) of events that occurs when two peers connect, negotiate a protocol, and open stream(s)
- [x] [Literature bibliography](https://github.com/libp2p/libp2p/issues/56) - Kad paper, Coral paper, some Leslie Lamport classics, etc
- [ ] Switch/Swarm diagram
- [x] [Life of a libp2p connection](https://youtu.be/zcWHamr5m_k)
- [ ] Single entry point to conceptual level documentation - something we can point people to that links out to all videos, diagrammatic overviews, etc.
- [ ] Deeper dives into libp2p modules like:
   - [ ] DHT
   - [ ] PubSub architectures (flood, gossip, epi)
   - [ ] Peer Discovery mechanisms
- [ ] Spec 2.0 - define what implementors MAY, SHOULD, MUST do
- [ ] What to do about `libp2p/interface-*` repos and the interface standardization issue?
  - [ ] Do we actually want this? (lowest common denominator problem
  -  [ ] Interfaces vs conceptual architecture
  -  [ ] How to test conformance in arbitrary new language implementations
- [x] [Hackmd.io pad](https://hackmd.io/OqUbEdbRSG6CRojUiitYiA) @stuckinaboot and @zixuanzh - maybe we can use this content somehow?
- [ ] Ideas in https://github.com/libp2p/libp2p/issues/58

cc @raulk @Mikerah

**Comment by DannyS03** [comment]
Recently, this issue was transferred over. However, since its last activity, much of the scope here has been addressed, making it outdated. Additionally, newer issues have outlined the tasks that need to be completed.
